version: "3.7"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks: 
      - my-stream-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    networks: 
      - my-stream-network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  consumer: 
    build: 
      context: ./
      dockerfile: ./Consumer/Dockerfile
    image: stream_consumer
    volumes:
      - "./jobs/:/tmp/jobs"
    networks: 
      - my-stream-network
      
  jupyter-lab:
    hostname: jupyter-lab
    networks:
      - my-stream-network
    build:
      dockerfile: ./jupyter-lab/Dockerfile
      context: ./
    image: jupyter_lab
    volumes:
      - "./notebooks/:/home/jovyan/notebooks"
    security_opt:
      - label=disable
    ports:
      - "8888:8888"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
    my-stream-network:
        name: my-stream-network
